pages:
  stage: deploy
  script:
  - ln -s /var/lib/zhf data
  - ./scripts/render-page.sh
  interruptible: true
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  resource_group: production
  tags:
    - helsinki-hydra-builder01
